apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8og0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8og0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8og0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8og0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8og0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mhxq-tenant/rhtap-demo-app/hacbs-test-project-8og0@sha256:f1aea4bcb07a60a27b88f01b89802241e90648c399a0190eb6e44be829eb0d6f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
